name: hideandseek
version: '0.2.2a'
main: com.tempce.hideandseek.Hideandseek
api-version: '1.21'
load: STARTUP
depend: [NBTAPI]
authors: ["あっきー(akki__)"]
commands:
  hideandseek:
    permission: hideandseek.admin
    aliases: [has]
    usage: /<command>
  map:
    permission: hideandseek.admin
    usage: /<command>
  event:
    permission: hideandseek.admin
    usage: /<command>
  shop:
    usage: /<command>
    aliases: [s]
permissions:
  hideandseek.*:
    children:
      hideandseek.admin: true
  hideandseek.admin:
    default: op
